name = "libui_ng_prebuilt_jll_packager"
uuid = "5c41e9d9-069e-44f2-ae18-c0dbe270cc58"
version = "0.1.0"
authors = ["Fumiya Funatsu <funatsu.fumiya@gmail.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[compat]
ArgParse = "1.2.0"
